name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      plugin-id: ${{ steps.metadata.outputs.plugin-id }}
      plugin-version: ${{ steps.metadata.outputs.plugin-version }}
    env:
      GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run build

      - name: Sign plugin
        run: npm run sign
        if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN != '' }}

      - name: Package plugin
        run: npm run package

      - name: Get plugin metadata
        id: metadata
        run: |
          echo "plugin-id=$(node -p "require('./src/plugin.json').id")" >> $GITHUB_OUTPUT
          echo "plugin-version=$(node -p "require('./src/plugin.json').info.version")" >> $GITHUB_OUTPUT

      - name: Validate plugin
        run: |
          docker run --pull=always \
            -v $PWD/cybertec-pev-panel.zip:/archive.zip \
            grafana/plugin-validator-cli -analyzer=metadatavalid /archive.zip

      - uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.metadata.outputs.plugin-id }}-${{ steps.metadata.outputs.plugin-version }}
          path: cybertec-pev-panel.zip
          retention-days: 5
